spring.application.name=showcase

spring.r2dbc.url=r2dbc:h2:mem:///~/usersdb;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;
spring.r2dbc.username=sa
spring.r2dbc.password=
spring.r2dbc.pool.enabled=true
spring.r2dbc.pool.initial-size=10
spring.r2dbc.pool.max-size=50
spring.r2dbc.pool.max-idle-time=30s
spring.r2dbc.pool.max-life-time=10m
spring.r2dbc.pool.validation-query=SELECT 1

spring.liquibase.url=jdbc:h2:mem:~/usersdb;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;
spring.liquibase.user=sa
spring.liquibase.password=
spring.liquibase.enabled=true
spring.liquibase.contexts=prod
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=6379

mymarket.upload.images.dir=upload/images
mymarket.redis.time-to-live=60

paymentsService.url=http://${PAYMENT_HOST:localhost}:${PAYMENT_PORT:8081}

spring.security.oauth2.client.registration.keycloak.client-id=payments-service-client
spring.security.oauth2.client.registration.keycloak.client-secret=${KEYCLOAK_SECRET:5xgpkHMU7yKb3FvB6Mu11wG152WpAIt6}
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=client_credentials
spring.security.oauth2.client.provider.keycloak.token-uri=http://${KEYCLOAK_HOST:localhost}:${KEYCLOAK_PORT:8082}/realms/my-market-app-realm/protocol/openid-connect/token
