spring.application.name=payment
server.port=8081
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://${KEYCLOAK_HOST:localhost}:${KEYCLOAK_PORT:8082}/realms/my-market-app-realm/protocol/openid-connect/certs
